language: node_js
node_js:
  - '6'
# env:
#   - CXX=g++-4.8
# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8
branches:
  only: 
    - master
script:
  - npm run test
after_success:
  - npm run coveralls
cache: npm
deploy:
  provider: npm
  email: ahmadbamieh@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master